name: salat
description: Salat Times App for Muslims in Bizerte
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21